package com.ssafy.bangrang.domain.map.model.vo;

public enum RegionType {
    KOREA, SEOUL, BUSAN, INCHEON, GWANGJU, DAEJEON, DAEGU, ULSAN, SEJONG, JEJU, GANGWON, GYEONGGI
    ,GYEONGNAM, GYEONGBUK, JEOLLANAM, JEOLLABUK, CHUNGNAM, CHUNGBUK
}
